source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'rails-api'
gem 'spring', :group => :development
gem 'devise'
gem 'rack-cors', :require => 'rack/cors'

group :test, :development do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'mysql2', '~> 0.3.18'
end

group :test do
  gem 'faker'
  gem 'shoulda', '~> 3.5'
end

 group :production do
  gem 'pg'
 end
